#ifndef MK1MF_BUILD
  /* auto-generated by crypto/Makefile for crypto/cversion.c */
  #define CFLAGS "arm-linux-gnueabihf-gcc -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DOPENSSL_NO_HEARTBEATS -DTERMIO -O3 -Wall"
  #define PLATFORM "linux-armv4"
  #define DATE "Fri Sep 25 13:32:29 CST 2015"
#endif
