// auto generated by configure
#ifndef SRS_AUTO_HEADER_HPP
#define SRS_AUTO_HEADER_HPP

#define SRS_AUTO_BUILD_TS "1443158472"
#define SRS_AUTO_BUILD_DATE "2015-09-25 13:21:13"
#define SRS_AUTO_UNAME "Linux debian-armhf 3.4.0-g037044b-dirty #7 SMP PREEMPT Thu Sep 17 16:36:50 CST 2015 armv7l GNU/Linux"
#define SRS_AUTO_USER_CONFIGURE " --with-arm-ubuntu12 --with-ssl --with-hls --log-verbose --prefix=/home/rtmpSRV/srs.git/out --without-librtmp --log-info"
#define SRS_AUTO_CONFIGURE "--prefix=/home/rtmpSRV/srs.git/out --with-hls --with-dvr --without-nginx --with-ssl --without-ffmpeg --with-transcode --with-ingest --with-stat --with-http-callback --with-http-server --with-http-api --without-librtmp --without-research --without-utest --without-gperf --without-gmc --without-gmp --without-gcp --without-gprof --with-arm-ubuntu12 --without-mips-ubuntu12 --static --log-verbose --log-info --log-trace"

#define SRS_AUTO_EMBEDED_TOOL_CHAIN "cc=arm-linux-gnueabihf-gcc gcc=arm-linux-gnueabihf-gcc g++=arm-linux-gnueabihf-g++ ar=arm-linux-gnueabihf-ar ld=arm-linux-gnueabihf-ld randlib=arm-linux-gnueabihf-ranlib"

#define SRS_AUTO_HTTP_PARSER
#define SRS_AUTO_HTTP_SERVER
#define SRS_AUTO_HTTP_API
#undef SRS_AUTO_NGINX
#define SRS_AUTO_DVR
#define SRS_AUTO_HLS
#define SRS_AUTO_HTTP_CALLBACK
#define SRS_AUTO_SSL
#undef SRS_AUTO_FFMPEG_TOOL
#define SRS_AUTO_FFMPEG_STUB
#define SRS_AUTO_TRANSCODE
#define SRS_AUTO_INGEST
#define SRS_AUTO_STAT
#undef SRS_AUTO_GPERF
#undef SRS_AUTO_GPERF_MC
#undef SRS_AUTO_GPERF_MP
#undef SRS_AUTO_GPERF_CP
#define SRS_AUTO_EMBEDED_CPU
#define SRS_AUTO_ARM_UBUNTU12
#undef SRS_AUTO_MIPS_UBUNTU12

#define SRS_AUTO_VERBOSE
#define SRS_AUTO_INFO
#define SRS_AUTO_TRACE

#define SRS_AUTO_PREFIX "/home/rtmpSRV/srs.git/out"

#define SRS_AUTO_CONSTRIBUTORS "\
winlin<winlin@vip.126.com> \
wenjie.zhao<740936897@qq.com> \
xiangcheng.liu<liuxc0116@foxmail.com> \
naijia.liu<youngcow@youngcow.net> \
alcoholyi<alcoholyi@qq.com> \
byteman<wangchen2011@gmail.com> \
chad.wang<chad.wang.cn@gmail.com> \
suhetao<suhetao@gmail.com> \
Johnny<fengjihu@163.com> \
karthikeyan<keyanmca@gmail.com> \
StevenLiu<lq@chinaffmpeg.org> \
zhengfl<zhengfl_1989@126.com> \
tufang14<breadbean1449@gmail.com> \
"

#endif

